### ISSUE TITLE
Context

### ISSUE THREAD

**Issue by iantearle** [dezinezync/TiTokenField#1]
Just took me 5 minutes and a google search to realise what a token field actually was. A little context perhaps an image might be useful on the readme like how apple docs show. https://developer.apple.com/library/mac/documentation/Cocoa/Conceptual/TokenField_Guide/Introduction/Introduction.html

**Comment by dezinezync** [comment]
Sure thing, Ian! The README file needs to be redone and a lot of information needs to be included, rather than having the developer figure things out from the example app. This shall be done within the week, as I plan to complete the implementation and bump things to version 1.0 

Cheers.

**Comment by dezinezync** [comment]
@iantearle Then I thought to myself, why wait! Updated to 1.0, with some missing props, and a complete README and screenshot. Cheers!
